# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            An Nguyen
tagline:          'Home'
description:      'A glimpse into the life of a twenty-two-year-old who is doing her Masters degree at York Uni and moving to Vancouver this October to start working at <a href="https://home.kpmg.com/ca/en/home/about/offices/vancouver-1.html" target="_blank">KPMG</a> full time.'
url:              http://antnh6.github.io/sister
baseurl:          /sister/

author:
  name:           'An Nguyen'
  url:            https://www.linkedin.com/in/nguyenah/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
